account/urls.py
from django.conf.urls import url

urlpatterns = []

article/urls.py
from django.conf.urls import url
from . import views

app_name = 'article'

urlpatterns = [
    url(r'^$', views.article_list, name='list'),
    url(r'^create/$', views.article_create, name='create'),
    url(r'^(?P<slug>[\w-]+)/$', views.article_detail, name='detail')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/', include('article.urls')),
    path('account/', include('account.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models

# Create your models here.

article/models.py
from django.db import models


class Article(models.Model):
    title = models.CharField(max_length=30)
    slug = models.SlugField(blank=True)
    content = models.TextField(max_length=1000)
    date = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(blank=True)

    def __str__(self):
        return f'{self.title}'

article/forms.py
from django import forms
from .models import Article


class CreateArticle(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['id', 'title', 'content', 'image', 'slug']

account/views.py
from django.shortcuts import render

# Create your views here.

article/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from . import forms
from .models import Article


def article_list(request):
    articles = Article.objects.all().order_by('date')
    return render(request, 'article_list.html', {'articles': articles})


def article_detail(request, slug):
    article = Article.objects.get(slug=slug)
    return render(request, 'article_detail.html', {'article': article})


def article_create(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('article:list')
    else:
        form = forms.CreateArticle()
    return render(request, 'new_article.html', {'form': form})

article/templates/article_detail.html
{% extends 'base.html' %} {% block content %}

<div class="container">
  <img src="{{ article.image.url }}" width="400px" height="auto" />
  <h1>{{article.title}}</h1>
  <h5>{{article.date}}</h5>
  <p>{{article.content}}</p>
</div>

{% endblock %}

article/templates/article_list.html
{% extends 'base.html' %} {% block content %}
<div class="container">
  <ul>
    {% for article in articles %}
    <li>
      <h3>{{article.title}}</h3>
      <h6>{{article.date}}</h6>
      <p>{{article.content}}</p>
    </li>
    {% endfor %}
  </ul>
</div>
{% endblock %}

article/templates/new_article.html
{% extends 'base.html' %} {% block content %}

<form
  action="{% url 'article:create' %}"
  method="post"
  enctype="multipart/form-data"
>
  {% csrf_token %} {{form}}
  <input type="submit" value="create" />
</form>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Document</title>
  </head>
  <body>
    {% include 'navbar.html' %} {% block content %} {% endblock %}
  </body>
</html>

templates/navbar.html
<ul>
  <li>login</li>
  <li>home</li>
</ul>